Repository practice-enterprise/canvas-discord-bot, pull requests merged in 2020-11, with the labels that each got.

#20 Add tokenizer
  src/util/tokenizer.ts
Labels: Priority: Critical, Type: Maintenance

#22 Fix line break error & formattor refactor
  .eslintrc.json
  package.json
  src/discord.ts
  src/util/formatter.ts
Labels: Priority: Low, Status: Completed, Type: Maintenance

#21 Debugger tools for VS Code
  .vscode/launch.json
Labels: Priority: Low, Type: Maintenance
